version: '3.8'
services:
  libraryapi:
    image: libraryapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"  # Maps port 80 in the container to port 8000 on your host
    volumes:
      - type: volume
        source: sqlite-data
        target: /app/Data
    environment:
      - ConnectionStrings__SQLiteConnection=Data Source=/app/Data/LibraryDB.db;

volumes:
  sqlite-data:
    name: libraryapi-sqlite-data